### ISSUE TITLE
First unit test for recognizer() can fail when it really shouldn't

### ISSUE THREAD

**Issue by pisymbol** [udacity/AIND-Recognizer#14]
The function recognize() in my_recognizer.py as part of Part 3 of this project is suppose to do two things:

1) Calculate the probabilities (log likelihoods) of all the test samples given the training models
2) Make a guess based on those log likelihoods

However, one of the unittests can fail if all the training models fail to yield a score for a given test sample which means the resulting list of dicts returned for "probabilities" will not have the same length as the number of test samples and thus the student will see something like:

"Number of training word probabilities in test item dictionary incorrect.")
AssertionError: 107 != 112 : Number of training word probabilities in test item dictionary incorrect.

The above is from the following line in the unit test case TestRecognize of asl_test.py:

 def test_recognize_probabilities_interface(self):
        probs, _ = recognize(self.models, self.test_set)
        self.assertEqual(len(probs), self.test_set.num_items, "Number of test items in probabilities list incorrect.")

I think given there is a possibility that all of the SelectorConstant models can fail to yield a score for a test sample (I found this issue somewhat illuminating since this is what I see occasionally: https://github.com/hmmlearn/hmmlearn/issues/101), the unit test should be more lenient regarding comparing numbers or else the project has to guarantee that a score() can always be generated for all the test word items.

NOTE: To pass this unit test I had to set float('-inf') for certain words which again, is not obvious.

**Comment by danainschool** [comment]
It sounds like you were able to solve the problem by catching failed models and providing a substitute probability.  I do see your point though... it is not strictly necessary for the recognition to have all 112 words defined in each probability dictionary in order to decode.  The last cell for the optional Part 4 will end up with NaN values in it if there are any missing dictionary items, however, though that is not necessarily a big problem either.  I am going to go ahead and remove the assertion that the first dictionary be 112 words.   The length of the list must be 112, however as positioning is dependent on the test word list indices.

Just to clarify, it is still important for the assertion you cited later in your post to remain: 
self.assertEqual(len(probs), self.test_set.num_items....)
This must be 112 because it is indexed to the test word numbers.  The dictionaries tested, i.e. probs[0] and probs[-1] do not necessarily have to include results from every models in order for the recognizer to work.

**Comment by pisymbol** [comment]
Dana, you got it! Thank you! I think that is the right move here.
